# Validates the caddyfile configuration
- name: Validate caddy configuration
  listen: caddy-validate
  become: true
  become_user: "{{ caddy_user }}"
  command: "{{ caddy_path }} -conf={{ caddy_config_path }} -validate"

# Restarts the caddy service
- name: Restart caddy
  listen: restart-caddy
  become: true
  systemd:
    daemon_reload: yes
    name: caddy
    state: restarted
