---
# Unzip binaries TODO
- name: "Download and unarchive pgweb {{ pgweb_version }}"
  unarchive:
    src: "https://github.com/sosedoff/pgweb/releases/download/{{ pgweb_version }}/pgweb_linux_amd64.zip"
    dest: "/usr/bin"
    remote_src: yes
    mode: 0755

# Rename binary to from pgweb_linux_amd64
- name: Rename pgweb_linux_amd64 binary to pgweb
  command: mv /usr/bin/pgweb_linux_amd64 /usr/bin/pgweb

# Install systemd unit and start service
- name: Install pgweb systemd unit
  become: true
  template:
    src: pgweb.service.tmpl
    dest: /etc/systemd/system/pgweb.service
    mode: 0600
  register: pgweb_service_result

# Start pgweb
- name: Start pgweb
  become: true
  systemd:
    daemon_reload: yes
    name: pgweb
    state: started
    enabled: true
  notify: restart-pgweb
